# Generated by Django 5.0.6 on 2024-07-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_hiring_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hiring_skills',
        ),
    ]
