# Generated by Django 5.0.6 on 2024-07-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_hiring_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(default='job_seeker', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
