# Generated by Django 5.0.6 on 2024-08-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_github_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github_access_token',
        ),
    ]
