# Generated by Django 5.0.6 on 2024-08-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_github_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='looking_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
