# Generated by Django 5.0.6 on 2024-10-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_achievements_customuser_job_hirer_ranking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='available_for_work_from_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_stage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hiring_skills',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='how_heard_about_codeunity',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job_hirer_ranking',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job_seeker_ranking',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='open_to_roles',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_annual_pay',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_hourly_pay',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='primary_role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='product_service',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='race_ethnicity',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='spoken_languages',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='working_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='x',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='JobHirerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('working_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_photo', models.ImageField(blank=True, null=True, upload_to='company_photos/')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('product_service', models.CharField(blank=True, max_length=255, null=True)),
                ('looking_for', models.CharField(choices=[('freelance', 'Freelance Contractor'), ('full_time', 'Full Time Employee')], max_length=50)),
                ('job_hirer_ranking', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_hirer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('available_for_work_from_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('job_seeker_ranking', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('race_ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=50, null=True)),
                ('how_heard_about_codeunity', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
