# Generated by Django 5.0.6 on 2024-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_personalinfo_race_ethnicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhirerprofile',
            name='job_hirer_ranking',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='available_for_work_from_date',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='job_seeker_ranking',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='x',
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
