# Generated by Django 5.0.6 on 2024-10-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_jobseekerprofile_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_permissions': (), 'managed': True, 'permissions': ()},
        ),
    ]
