# Generated by Django 5.0.6 on 2024-10-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_jobseekerprofile_years_of_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhirerprofile',
            old_name='working_email',
            new_name='work_email',
        ),
    ]
