# Generated by Django 5.0.6 on 2024-10-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_personalinfo_gender_self_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('black_african', 'Black / African-American'), ('east_asian', 'East Asian (including Chinese, Japanese, Korean, and Mongolian)'), ('hispanic_latino', 'Hispanic or Latino/a/x'), ('middle_eastern', 'Middle Eastern'), ('native_american', 'Native American or Alaskan Native'), ('pacific_islander', 'Pacific Islander'), ('south_asian', 'South Asian (including Bangladeshi, Bhutanese, Indian, Nepali, Pakistani, and Sri Lankan)'), ('southeast_asian', 'Southeast Asian (including Burmese, Cambodian, Filipino, Hmong, Indonesian, Laotian, Malaysian, Mien, Singaporean, Thai, and Vietnamese)'), ('white', 'White'), ('prefer_not_say', 'Prefer not to say')], max_length=50, null=True),
        ),
    ]
