# Generated by Django 5.0.6 on 2024-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_personalinfo_race_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhirerprofile',
            name='company_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
