# Generated by Django 5.0.6 on 2024-08-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='invoice_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='invoice_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='invoice_notes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pay_later',
        ),
    ]
