# Generated by Django 5.0.6 on 2024-10-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_location_restriction_job_job_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_id',
            new_name='applicant',
        ),
    ]
