# Generated by Django 5.0.6 on 2024-10-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_applicant_id_jobapplication_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary_max',
            new_name='annual_salary_max',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary_min',
            new_name='annual_salary_min',
        ),
    ]
