# Generated by Django 5.0.6 on 2024-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='annual_salary_max',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='annual_salary_min',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
