# Generated by Django 5.0.6 on 2024-10-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_annual_salary_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='resume',
            new_name='resume_url',
        ),
    ]
