# Generated by Django 5.0.6 on 2024-10-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_rename_resume_jobapplication_resume_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_logo_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
    ]
