# Generated by Django 5.0.6 on 2024-10-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_remove_job_company_logo_remove_job_company_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
